name: DevOps Challenge CI CD
run-name: ${{ github.actor }} is running pipeline 🚀
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test Flask App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        working-directory: ./devops-challenge
        run: |
          pytest tests/

  build-push:
    name: docker-build-push
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ${{ github.ref_name }}
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Git SHA
        id: vars
        run: echo "GIT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_REPO }}:latest
            ${{ vars.DOCKERHUB_REPO }}:v-${{ env.GIT_SHA }}